#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it on the first line, but has a "next best alternative", that is
#       a strong hint of the problem.
#       Please see the Gradle user guide chapter on Troubleshooting for more details.
#
#   (2) The GW_HOME environment variable is not required to run this script,
#       but will save you a lot of typing in most of the commands it will be run as:
#
#       $ gradlew
#       $ gradlew.bat
#       $ gradlew.cmd
#
#   (3) When using the Cygwin environment, your M2_HOME (maven) is not related at all
#       to the location of the Gradle installation.
#
#   (4) Never quote the return value of `pwd`, there are people who have blanks in
#       the name of their current directory and it could cause "`cd /d
#       `" to fail.
#
#   (5) Prior to Gradle 2.14, `int >
#       `GW_CMD%"
#       set
#
#   (6) Now we take advantage of the internal Gradle daemon to speed up builds.
#       Depending on the system configuration, the overhead of starting Gradle in
#       direct mode is avoided in most of the time.
#       Without the "-e" switch, all tests in packages are executed.
#
#   (7) Gradle will search for its installation under GW_HOME if set to nothing
#
# Gradle startup script for UN*X
#
###############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a symlink
pwd -P
cd -P "$(dirname "$0")"
APP_HOME=$(pwd -P)
cd -

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" -Xms64m"'

# Use the maximum available, or set MAX_FD != unlimited.
MAX_FD=maximum

# Tell sh how to exit with a nonzero exit code and exit.
die() {
  echo "$@"
  exit 1
}

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$msys" ; then
  case $host_os in                #((
    darwin*) ;;
  esac
fi

case $host_os in #((
dawin*) ;;
esac

if [ "$JAVA_HOME" != "" ] ; then
  JAVA_HOME="$JAVA_HOME"
  if [ ! -d "$JAVA_HOME" ] ; then
   die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
  fi
else
  JAVA_HOME=$(javapath)
fi

if [ -z "$JAVA_HOME" ] ; then
  die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the location of your Java installation."
fi

if [ -n "${BASH_VERSION+set}" ] ; then
  # shellcheck disable=SC2034
  BASH_ENV=$( dirname "${BASH_SOURCE[0]}" )/gradle.properties
  [ -s "$BASH_ENV" ] && . "$BASH_ENV"
fi

if [ -n "${ZSH_VERSION+set}" ] ; then
  setopt SH_WORD_SPLIT
  NULLCMD=:
  emulate -L sh
fi

exec "$JAVACMD" -server $GRADLE_OPTS "${JAVA_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
